[package]
name = "compromise-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[lib]
proc-macro = true

[features]
panicking = []

[dependencies]
proc-macro2 = "1"
proc-macro-crate = "3.5"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
compromise = { path = "../compromise" }
trybuild = "1"
